name: Package Extension

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: package with vsce
        run: |
          npm install -g vsce
          vsce package --target web
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Extension Package
          path: ./*.vsix
